/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: connect.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "connect.pb-c.h"
void   contrast__api__connect__pair__init
                     (Contrast__Api__Connect__Pair         *message)
{
  static const Contrast__Api__Connect__Pair init_value = CONTRAST__API__CONNECT__PAIR__INIT;
  *message = init_value;
}
size_t contrast__api__connect__pair__get_packed_size
                     (const Contrast__Api__Connect__Pair *message)
{
  assert(message->base.descriptor == &contrast__api__connect__pair__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t contrast__api__connect__pair__pack
                     (const Contrast__Api__Connect__Pair *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &contrast__api__connect__pair__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t contrast__api__connect__pair__pack_to_buffer
                     (const Contrast__Api__Connect__Pair *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &contrast__api__connect__pair__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Contrast__Api__Connect__Pair *
       contrast__api__connect__pair__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Contrast__Api__Connect__Pair *)
     protobuf_c_message_unpack (&contrast__api__connect__pair__descriptor,
                                allocator, len, data);
}
void   contrast__api__connect__pair__free_unpacked
                     (Contrast__Api__Connect__Pair *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &contrast__api__connect__pair__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   contrast__api__connect__request__init
                     (Contrast__Api__Connect__Request         *message)
{
  static const Contrast__Api__Connect__Request init_value = CONTRAST__API__CONNECT__REQUEST__INIT;
  *message = init_value;
}
size_t contrast__api__connect__request__get_packed_size
                     (const Contrast__Api__Connect__Request *message)
{
  assert(message->base.descriptor == &contrast__api__connect__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t contrast__api__connect__request__pack
                     (const Contrast__Api__Connect__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &contrast__api__connect__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t contrast__api__connect__request__pack_to_buffer
                     (const Contrast__Api__Connect__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &contrast__api__connect__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Contrast__Api__Connect__Request *
       contrast__api__connect__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Contrast__Api__Connect__Request *)
     protobuf_c_message_unpack (&contrast__api__connect__request__descriptor,
                                allocator, len, data);
}
void   contrast__api__connect__request__free_unpacked
                     (Contrast__Api__Connect__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &contrast__api__connect__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   contrast__api__connect__response__init
                     (Contrast__Api__Connect__Response         *message)
{
  static const Contrast__Api__Connect__Response init_value = CONTRAST__API__CONNECT__RESPONSE__INIT;
  *message = init_value;
}
size_t contrast__api__connect__response__get_packed_size
                     (const Contrast__Api__Connect__Response *message)
{
  assert(message->base.descriptor == &contrast__api__connect__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t contrast__api__connect__response__pack
                     (const Contrast__Api__Connect__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &contrast__api__connect__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t contrast__api__connect__response__pack_to_buffer
                     (const Contrast__Api__Connect__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &contrast__api__connect__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Contrast__Api__Connect__Response *
       contrast__api__connect__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Contrast__Api__Connect__Response *)
     protobuf_c_message_unpack (&contrast__api__connect__response__descriptor,
                                allocator, len, data);
}
void   contrast__api__connect__response__free_unpacked
                     (Contrast__Api__Connect__Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &contrast__api__connect__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor contrast__api__connect__pair__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Pair, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Pair, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned contrast__api__connect__pair__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange contrast__api__connect__pair__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor contrast__api__connect__pair__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "contrast.api.connect.Pair",
  "Pair",
  "Contrast__Api__Connect__Pair",
  "contrast.api.connect",
  sizeof(Contrast__Api__Connect__Pair),
  2,
  contrast__api__connect__pair__field_descriptors,
  contrast__api__connect__pair__field_indices_by_name,
  1,  contrast__api__connect__pair__number_ranges,
  (ProtobufCMessageInit) contrast__api__connect__pair__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor contrast__api__connect__request__field_descriptors[23] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, client_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_count",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, message_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp_ms",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_name",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, app_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_language",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, app_language),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, command),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_line",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, request_line),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normalized_uri",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, normalized_uri),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_ip",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, client_ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_ip_version",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, client_ip_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_port",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, client_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_ip",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, server_ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_ip_version",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, server_ip_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_port",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, server_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_headers",
    20,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Contrast__Api__Connect__Request, n_request_headers),
    offsetof(Contrast__Api__Connect__Request, request_headers),
    &contrast__api__connect__pair__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_body",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, request_body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response_code",
    24,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, response_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response_headers",
    26,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Contrast__Api__Connect__Request, n_response_headers),
    offsetof(Contrast__Api__Connect__Request, response_headers),
    &contrast__api__connect__pair__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response_body",
    28,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, response_body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connector_type",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, connector_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connector_version",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Request, connector_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned contrast__api__connect__request__field_indices_by_name[] = {
  5,   /* field[5] = app_language */
  4,   /* field[4] = app_name */
  0,   /* field[0] = client_id */
  10,   /* field[10] = client_ip */
  11,   /* field[11] = client_ip_version */
  12,   /* field[12] = client_port */
  7,   /* field[7] = command */
  21,   /* field[21] = connector_type */
  22,   /* field[22] = connector_version */
  2,   /* field[2] = message_count */
  9,   /* field[9] = normalized_uri */
  1,   /* field[1] = pid */
  17,   /* field[17] = request_body */
  16,   /* field[16] = request_headers */
  8,   /* field[8] = request_line */
  20,   /* field[20] = response_body */
  18,   /* field[18] = response_code */
  19,   /* field[19] = response_headers */
  13,   /* field[13] = server_ip */
  14,   /* field[14] = server_ip_version */
  15,   /* field[15] = server_port */
  3,   /* field[3] = timestamp_ms */
  6,   /* field[6] = uuid */
};
static const ProtobufCIntRange contrast__api__connect__request__number_ranges[8 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 14, 10 },
  { 22, 17 },
  { 24, 18 },
  { 26, 19 },
  { 28, 20 },
  { 30, 21 },
  { 0, 23 }
};
const ProtobufCMessageDescriptor contrast__api__connect__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "contrast.api.connect.Request",
  "Request",
  "Contrast__Api__Connect__Request",
  "contrast.api.connect",
  sizeof(Contrast__Api__Connect__Request),
  23,
  contrast__api__connect__request__field_descriptors,
  contrast__api__connect__request__field_indices_by_name,
  8,  contrast__api__connect__request__number_ranges,
  (ProtobufCMessageInit) contrast__api__connect__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor contrast__api__connect__response__field_descriptors[5] =
{
  {
    "timestamp_ms",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Response, timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Response, uuid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "track_request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Response, track_request),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "security_exception",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Response, security_exception),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "security_message",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Contrast__Api__Connect__Response, security_message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned contrast__api__connect__response__field_indices_by_name[] = {
  3,   /* field[3] = security_exception */
  4,   /* field[4] = security_message */
  0,   /* field[0] = timestamp_ms */
  2,   /* field[2] = track_request */
  1,   /* field[1] = uuid */
};
static const ProtobufCIntRange contrast__api__connect__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor contrast__api__connect__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "contrast.api.connect.Response",
  "Response",
  "Contrast__Api__Connect__Response",
  "contrast.api.connect",
  sizeof(Contrast__Api__Connect__Response),
  5,
  contrast__api__connect__response__field_descriptors,
  contrast__api__connect__response__field_indices_by_name,
  1,  contrast__api__connect__response__number_ranges,
  (ProtobufCMessageInit) contrast__api__connect__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
