contrast: 
  url: https://alpha.contrastsecurity.com/Contrast
  user_name: agent_55da7aab-9759-496f-bec6-caf4326cf651@ContrastSecurity
  api_key: wwEHMnYEIAujE03f
  service_key: 7FCZUPJPDES9X0G6
agent: 
  service: 
    logger: 
      path: contrast_service.log
      level: ERROR
    host: 127.0.0.1
    port: 30555
