#!/bin/bash

pushd "vendor"
pushd "nginx-1.13.9"

module_type="--add-dynamic-module"
if [ "$1" = "static" ]; then
    module_type="--add-module"
fi

# NOTE: per protobuf-c link against the libprotobuf-c support library
# https://github.com/protobuf-c/protobuf-c#Synposis
CFLAGS="-g -O0 -Wall -Wextra -Wno-unused-parameter " ./configure \
    --with-debug \
    --prefix=$(pwd)/../../build/nginx \
    --conf-path=conf/nginx.conf \
    --error-log-path=logs/error.log \
    --http-log-path=logs/access.log \
    "$module_type"=../../ 
make -j4
make install
popd
popd
